# Generated by Django 4.2.7 on 2023-11-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0002_rename_crew_id_maintenancetask_crew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintainancecrew',
            old_name='crew_ID',
            new_name='crew_id',
        ),
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='maintenance_task_ID',
            new_name='maintenance_task_id',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_ID',
            new_name='train_id',
        ),
    ]
