# Generated by Django 4.2.7 on 2023-11-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0003_rename_crew_id_maintainancecrew_crew_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='bool_disability_access',
            new_name='has_disability_access',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='bool_folding_tables',
            new_name='has_folding_tables',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='bool_food_service',
            new_name='has_food_service',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='bool_luggage_storage',
            new_name='has_luggage_storage',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='bool_reclining_seats',
            new_name='has_reclining_seats',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='bool_vending_machine',
            new_name='has_vending_machine',
        ),
    ]
