# Generated by Django 4.2.7 on 2023-11-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0004_rename_bool_disability_access_train_has_disability_access_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceTask',
            new_name='MaintainanceTask',
        ),
    ]
