# Generated by Django 4.2.7 on 2023-11-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_maintain', '0005_rename_maintenancetask_maintainancetask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintainanceCrew',
            new_name='MaintenanceCrew',
        ),
        migrations.RenameModel(
            old_name='MaintainanceTask',
            new_name='MaintenanceTask',
        ),
    ]
